#ifndef LIBNFITS_KEYWORDS_H
#define LIBNFITA_KEYWORDS_H

// standard keywords for FITS files
#define	FITS_KEYWORD_AUTHOR             "AUTHOR"
#define	FITS_KEYWORD_BITPIX             "BITPIX"
#define	FITS_KEYWORD_BLANK              "BLANK"
#define	FITS_KEYWORD_BLOCKED            "BLOCKED"
#define	FITS_KEYWORD_BSCALE             "BSCALE"
#define	FITS_KEYWORD_BUNIT              "BUNIT"
#define	FITS_KEYWORD_BZERO              "BZERO"
#define	FITS_KEYWORD_CHECKSUM           "CHECKSUM"
#define	FITS_KEYWORD_COMMENT            "COMMENT"
#define	FITS_KEYWORD_CONTINUE           "CONTINUE"
#define	FITS_KEYWORD_DATAMAX            "DATAMAX"
#define	FITS_KEYWORD_DATAMIN            "DATAMIN"
#define	FITS_KEYWORD_DATASUM            "DATASUM"
#define	FITS_KEYWORD_DATE               "DATE"
#define	FITS_KEYWORD_DATE_OBS           "DATE-OBS"
#define	FITS_KEYWORD_END                "END"
#define	FITS_KEYWORD_EPOCH              "EPOCH"
#define	FITS_KEYWORD_EQUINOX            "EQUINOX"
#define	FITS_KEYWORD_EXTEND             "EXTEND"
#define	FITS_KEYWORD_EXTLEVEL           "EXTLEVEL"
#define	FITS_KEYWORD_EXTNAME            "EXTNAME"
#define	FITS_KEYWORD_EXTVER             "EXTVER"
#define	FITS_KEYWORD_FZALG              "FZALG"
#define	FITS_KEYWORD_FZALGOR            "FZALGOR"
#define	FITS_KEYWORD_FZTILELN           "FZTILELN"
#define	FITS_KEYWORD_GCOUNT             "GCOUNT"
#define	FITS_KEYWORD_GROUPS             "GROUPS"
#define	FITS_KEYWORD_HISTORY            "HISTORY"
#define	FITS_KEYWORD_INHERIT            "INHERIT"
#define	FITS_KEYWORD_INSTRUME           "INSTRUME"
#define	FITS_KEYWORD_NAXIS              "NAXIS"
#define	FITS_KEYWORD_OBJECT             "OBJECT"
#define	FITS_KEYWORD_OBSERVER           "OBSERVER"
#define	FITS_KEYWORD_ORIGIN             "ORIGIN"
#define	FITS_KEYWORD_PCOUNT             "PCOUNT"
#define	FITS_KEYWORD_PSCAL              "PSCAL"
#define	FITS_KEYWORD_PTYPE              "PTYPE"
#define	FITS_KEYWORD_PZERO              "PZERO"
#define	FITS_KEYWORD_REFERENC           "REFERENC"
#define	FITS_KEYWORD_SIMPLE             "SIMPLE"
#define	FITS_KEYWORD_TBCOL              "TBCOL"
#define	FITS_KEYWORD_TDIM               "TDIM"
#define	FITS_KEYWORD_TDISP              "TDISP"
#define	FITS_KEYWORD_TDMAX              "TDMAX"
#define	FITS_KEYWORD_TDMIN              "TDMIN"
#define	FITS_KEYWORD_TELESCOP           "TELESCOP"
#define	FITS_KEYWORD_TFIELDS            "TFIELDS"
#define	FITS_KEYWORD_TFORM              "TFORM"
#define	FITS_KEYWORD_THEAP              "THEAP"
#define	FITS_KEYWORD_TLMAX              "TLMAX"
#define	FITS_KEYWORD_TLMIN              "TLMIN"
#define	FITS_KEYWORD_TNULL              "TNULL"
#define	FITS_KEYWORD_TSCAL              "TSCAL"
#define	FITS_KEYWORD_TTYPE              "TTYPE"
#define	FITS_KEYWORD_TUNIT              "TUNIT"
#define	FITS_KEYWORD_TZERO              "TZERO"
#define	FITS_KEYWORD_XTENSION           "XTENSION"
#define	FITS_KEYWORD_ZBITPIX            "ZBITPIX"
#define	FITS_KEYWORD_ZBLOCKED           "ZBLOCKED"
#define	FITS_KEYWORD_ZCMPTYPE           "ZCMPTYPE"
#define	FITS_KEYWORD_ZCTYP              "ZCTYP"
#define	FITS_KEYWORD_ZDATASUM           "ZDATASUM"
#define	FITS_KEYWORD_ZDITHER0           "ZDITHER0"
#define	FITS_KEYWORD_ZEXTEND            "ZEXTEND"
#define	FITS_KEYWORD_ZFORM              "ZFORM"
#define	FITS_KEYWORD_ZGCOUNT            "ZGCOUNT"
#define	FITS_KEYWORD_ZHECKSUM           "ZHECKSUM"
#define	FITS_KEYWORD_ZIMAGE             "ZIMAGE"
#define	FITS_KEYWORD_ZMASKCMP           "ZMASKCMP"
#define	FITS_KEYWORD_ZNAME              "ZNAME"
#define	FITS_KEYWORD_ZNAXIS             "ZNAXIS"
#define	FITS_KEYWORD_ZPCOUNT            "ZPCOUNT"
#define	FITS_KEYWORD_ZQUANTIZ           "ZQUANTIZ"
#define	FITS_KEYWORD_ZSIMPLE            "ZSIMPLE"
#define	FITS_KEYWORD_ZTABLE             "ZTABLE"
#define	FITS_KEYWORD_ZTENSION           "ZTENSION"
#define	FITS_KEYWORD_ZTHEAP             "ZTHEAP"
#define	FITS_KEYWORD_ZTILE              "ZTILE"
#define	FITS_KEYWORD_ZTILELEN           "ZTILELEN"
#define	FITS_KEYWORD_ZVAL               "ZVAL"
#define	FITS_KEYWORD_SPACES8            "        "

#define FITS_XTENSION_IMAGE             "IMAGE   "
#define FITS_XTENSION_TABLE             "TABLE   "
#define FITS_XTENSION_BINTABLE          "BINTABLE"

#endif // LIBNFITS_KEYWORDS_H
